## Analisis Teks

Untuk datasets dapat diunduh di http://archive.ics.uci.edu/ml/datasets.php

## BAGIAN 1

In [93]:
#memasukan modul yang digunakan
import pandas as pd

In [94]:
#encode('utf-8')
letak_data = 'C:/WinPython_64bit/notebooks/8. BELAJAR DATA SCIENCE/sms-spam-collection-dataset/spam.csv'
letak_data.encode('utf-8')

b'C:/WinPython_64bit/notebooks/8. BELAJAR DATA SCIENCE/sms-spam-collection-dataset/spam.csv'

In [95]:
#membuka letak_data untuk melihat encode
open(letak_data)

<_io.TextIOWrapper name='C:/WinPython_64bit/notebooks/8. BELAJAR DATA SCIENCE/sms-spam-collection-dataset/spam.csv' mode='r' encoding='cp1252'>

In [96]:
#membuka 5 data pertama
data = pd.read_csv(letak_data, encoding='cp1252')
data.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [97]:
#membuka 5 data terakhir
data.tail()

v1                                                 v2 Unnamed: 2  \
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN

In [98]:
#mengambil kolom data yang dibutuhkan 
#dalam hal ini hanya kolom v1 dan v2
data = data.iloc[:,[0,1]]
data.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [99]:
#statistika deskriptif data
data.describe()

v1                      v2
count   5572                    5572
unique     2                    5169
top      ham  Sorry, I'll call later
freq    4825                      30

In [100]:
#melihat ukuran data
data.shape

(5572, 2)

In [101]:
#melihat jumlah data ham dan spam
data.v1.value_counts()

ham     4825
spam     747
Name: v1, dtype: int64

In [102]:
#membuat kolom baru yang isinya kategori dari data yaitu ham : 0 dan spam : 1
#data['label_number'] = data.v1.map({'ham':0, 'spam':1})
data['label_number'] = data.v1.map({'ham':0, 'spam':1})

In [103]:
#melihat hasilnya
data.head()

v1                                                 v2  label_number
0   ham  Go until jurong point, crazy.. Available only ...             0
1   ham                      Ok lar... Joking wif u oni...             0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...             1
3   ham  U dun say so early hor... U c already then say...             0
4   ham  Nah I don't think he goes to usf, he lives aro...             0

In [104]:
#membuat variabel dependen dan independen
X = data.v2 #data teks
y = data.label_number #target

In [105]:
#melihat ukuran data dependen
X.shape

(5572,)

In [106]:
#melihat ukuran data independen
y.shape

(5572,)

In [107]:
from sklearn.cross_validation import train_test_split

In [108]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 13)

In [109]:
print(X_train.shape, X_test.shape)

(3900,) (1672,)


In [110]:
print(y_train.shape, y_test.shape)

(3900,) (1672,)


## BAGIAN 2
### CountVectorizer, Dtm Object, and Build Model

In [111]:
from sklearn.feature_extraction.text import CountVectorizer

In [112]:
vector = CountVectorizer()

In [113]:
vector.fit(X_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [114]:
X_train_dtmatrix = vector.transform(X_train)

In [115]:
print(X_train_dtmatrix.shape)

(3900, 7251)


In [116]:
#hasil dari vector.transform(X_train)
X_train_dtmatrix

<3900x7251 sparse matrix of type '<class 'numpy.int64'>'
	with 51672 stored elements in Compressed Sparse Row format>

In [117]:
X_test_dtmatrix = vector.transform(X_test)

In [118]:
print(X_test_dtmatrix.shape)

(1672, 7251)


In [119]:
#hasil dari vector.transform(X_test)
X_test_dtmatrix

<1672x7251 sparse matrix of type '<class 'numpy.int64'>'
	with 20663 stored elements in Compressed Sparse Row format>

## Model MultinomialNB

In [120]:
from sklearn.naive_bayes import MultinomialNB

In [121]:
model_nb = MultinomialNB()

In [122]:
model_nb.fit(X_train_dtmatrix, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [123]:
y_prediksi = model_nb.predict(X_test_dtmatrix)
y_prediksi

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

### Akurasi dan Confusion Matrix

In [124]:
from sklearn import metrics

In [125]:
metrics.accuracy_score(y_test, y_prediksi)

0.9880382775119617

In [126]:
metrics.confusion_matrix(y_test, y_prediksi)

array([[1436,    5],
       [  15,  216]], dtype=int64)

## Model Regresi Logistik 

In [127]:
from sklearn.linear_model import LogisticRegression

In [128]:
model_rl = LogisticRegression()

In [129]:
model_rl.fit(X_train_dtmatrix, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [130]:
y_prediksi_rl = model_rl.predict(X_test_dtmatrix)
y_prediksi_rl

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [131]:
metrics.accuracy_score(y_test, y_prediksi_rl)

0.9826555023923444

In [132]:
metrics.confusion_matrix(y_test, y_prediksi_rl)

array([[1436,    5],
       [  24,  207]], dtype=int64)

## BAGIAN 3
#### Catatan:  
    y_test < y_prediksi dalam hal ini 0 dan 1 
    0 < 1 dalam hal ini ham:0 dan spam:1

In [133]:
X_test[y_test < y_prediksi]

2418    Madam,regret disturbance.might receive a refer...
990                                          26th OF JULY
1259    We have sent JD for Customer Service cum Accou...
5044    We have sent JD for Customer Service cum Accou...
4555                              Gettin rdy to ship comp
Name: v2, dtype: object

In [134]:
len(X_test[y_test < y_prediksi])

5

In [135]:
# 1 > 0
X_test[y_test > y_prediksi]

3417    LIFE has never been this much fun and great un...
3862    Oh my god! I've found your number again! I'm s...
683     Hi I'm sue. I am 20 years old and work as a la...
1499    SMS. ac JSco: Energy is high, but u may not kn...
4211    Missed call alert. These numbers called but le...
1892    CALL 09090900040 & LISTEN TO EXTREME DIRTY LIV...
2773    How come it takes so little time for a child w...
1268    Can U get 2 phone NOW? I wanna chat 2 set up m...
855     Talk sexy!! Make new friends or fall in love i...
1457    CLAIRE here am havin borin time & am now alone...
2662    Hello darling how are you today? I would love ...
4142    In The Simpsons Movie released in July 2007 na...
2574    Your next amazing xxx PICSFREE1 video will be ...
954             Filthy stories and GIRLS waiting for your
68      Did you hear about the new \Divorce Barbie\"? ...
Name: v2, dtype: object

In [136]:
len(X_test[y_test > y_prediksi])

15

In [137]:
X_test[683]

"Hi I'm sue. I am 20 years old and work as a lapdancer. I love sex. Text me live - I'm i my bedroom now. text SUE to 89555. By TextOperator G2 1DA 150ppmsg 18+"

In [138]:
X_test[y_test > y_prediksi_rl]

3417    LIFE has never been this much fun and great un...
3862    Oh my god! I've found your number again! I'm s...
414     100 dating service cal;l 09064012103 box334sk38ch
683     Hi I'm sue. I am 20 years old and work as a la...
4211    Missed call alert. These numbers called but le...
1892    CALL 09090900040 & LISTEN TO EXTREME DIRTY LIV...
659     88800 and 89034 are premium phone services cal...
2773    How come it takes so little time for a child w...
1044    We know someone who you know that fancies you....
1268    Can U get 2 phone NOW? I wanna chat 2 set up m...
3883    A link to your picture has been sent. You can ...
3008    Update_Now - 12Mths Half Price Orange line ren...
2802                    FreeMsg>FAV XMAS TONES!Reply REAL
4392    RECPT 1/3. You have ordered a Ringtone. Your o...
3989    (Bank of Granite issues Strong-Buy) EXPLOSIVE ...
1457    CLAIRE here am havin borin time & am now alone...
2662    Hello darling how are you today? I would love ...
4142    In The

In [139]:
len(X_test[y_test > y_prediksi_rl])

24

In [140]:
X_test[y_test < y_prediksi_rl]

5085    Sorry i missed your call. Can you please call ...
3690    Sir, i am waiting for your call, once free ple...
1259    We have sent JD for Customer Service cum Accou...
5044    We have sent JD for Customer Service cum Accou...
2339    Cheers for the message Zogtorius. IåÕve been s...
Name: v2, dtype: object

In [141]:
len(X_test[y_test < y_prediksi_rl])

5

In [142]:
X_test[5044]

'We have sent JD for Customer Service cum Accounts Executive to ur mail id, For details contact us'

## BAGIAN 4

#### Menemukan kata yang paling banyak dari masing-masing kategori (spam dan ham)

In [143]:
#melihat vektor kata-kata di data train 
#vector.get_feature_names()
X_train_words = vector.get_feature_names()

In [144]:
#melihat banyaknya kata-kata di data train 
len(X_train_words)

7251

In [145]:
#melihat vektor kata-kata dari kata pertama sampai kata kelima atau 5 kata pertama
X_train_words[:5]

['00', '000', '008704050406', '0089', '0121']

In [146]:
#melihat 11 vektor kata-kata dari indeks kata ke 90 sampai 100 
X_train_words[89:100]

['08712400602450p',
 '08712400603',
 '08712402050',
 '08712402578',
 '08712402779',
 '08712402972',
 '08712404000',
 '08712405020',
 '08712405022',
 '08712460324',
 '08712466669']

In [147]:
#melihat 10 vektor kata-kata dari indeks kata ke 7000 sampai 7010 
X_train_words[7000:7010]

['wherevr',
 'wherre',
 'whether',
 'which',
 'while',
 'whilltake',
 'white',
 'whn',
 'who',
 'whole']

In [148]:
#melihat feature_count_
#melihat jumlah kata-kata
model_nb.feature_count_

array([[ 0.,  0.,  0., ...,  0.,  8.,  1.],
       [ 7., 20.,  2., ...,  1.,  0.,  0.]])

In [149]:
#melihat ukuran jumlah kata-kata
model_nb.feature_count_.shape

(2, 7251)

In [150]:
#melihat jumlah kata-kata untuk kategori ham
ham_words_count = model_nb.feature_count_[0,:]
ham_words_count

array([0., 0., 0., ..., 0., 8., 1.])

In [151]:
#melihat ukuran jumlah kata-kata kategori ham
ham_words_count.shape

(7251,)

In [152]:
#melihat jumlah kata-kata untuk kategori spam
spam_words_count = model_nb.feature_count_[1,:]
spam_words_count

array([ 7., 20.,  2., ...,  1.,  0.,  0.])

In [153]:
#membuat dataFrame vektor kata-kata dari kategori ham dan spam 
tokens = pd.DataFrame({'token' : X_train_words, 'ham' : ham_words_count, 'spam' : spam_words_count})

In [154]:
#melihat hasilnya
tokens.head()

token  ham  spam
0            00  0.0   7.0
1           000  0.0  20.0
2  008704050406  0.0   2.0
3          0089  0.0   1.0
4          0121  0.0   1.0

In [155]:
#membuat set_index('token')
tokens = tokens.set_index('token')

In [156]:
#melihat hasilnya
#melihat 5 vektor kata-kata pertama
tokens.head()

ham  spam
token                  
00            0.0   7.0
000           0.0  20.0
008704050406  0.0   2.0
0089          0.0   1.0
0121          0.0   1.0

In [157]:
#melihat 5 vektor kata-kata terakhir
tokens.tail()

ham  spam
token              
û_        8.0   0.0
û_thanks  1.0   0.0
ûªve      0.0   1.0
ûò        8.0   0.0
žö        1.0   0.0

In [158]:
#melihat jumlah vektor kata-kata dengan class_count_ dari kategori ham dan spam
model_nb.class_count_

array([3384.,  516.])

In [159]:
#menambahkan vektor kata-kata dari kategori ham dengan 10 point
tokens['ham'] = tokens.ham + 10 

In [160]:
#menambahkan vektor kata-kata dari kategori spam dengan 10 point
tokens['spam'] = tokens.spam + 10

In [161]:
#melihat hasilnya
#melihat 5 vektor kata-kata pertama
tokens.head()

ham  spam
token                   
00            10.0  17.0
000           10.0  30.0
008704050406  10.0  12.0
0089          10.0  11.0
0121          10.0  11.0

In [162]:
from __future__ import division

In [163]:
#membagi nilai masing-masing kolom ham dan spam dengan jumlah class_count_
#untuk tokens['ham']
#misalnya token '0121' maka nilai '10' dibagi '3384.'(jumlah kolom ham yang memiliki nilai tak nol)
tokens['ham'] = tokens.ham/model_nb.class_count_[0]

In [164]:
#membagi nilai masing-masing kolom ham dan spam dengan jumlah class_count_
#untuk tokens['spam']
#misalnya token '0121' maka nilai '11' dibagi '516.'(jumlah kolom ham yang memiliki nilai tak nol)
tokens['spam'] = tokens.spam/model_nb.class_count_[1]

In [165]:
#melihat hasilnya
tokens.head()

ham      spam
token                           
00            0.002955  0.032946
000           0.002955  0.058140
008704050406  0.002955  0.023256
0089          0.002955  0.021318
0121          0.002955  0.021318

In [166]:
#perbandingan nilai tokens.ham dan tokens.spam
#misalnya untuk token '0121' maka 0.002955 dibagi 0.021318
tokens['ham_to_spam_ratio'] = tokens.ham/tokens.spam

In [167]:
#melihat hasilnya
tokens.head()

ham      spam  ham_to_spam_ratio
token                                              
00            0.002955  0.032946           0.089695
000           0.002955  0.058140           0.050827
008704050406  0.002955  0.023256           0.127069
0089          0.002955  0.021318           0.138620
0121          0.002955  0.021318           0.138620

In [168]:
#melihat hasil tokens['ham_to_spam_ratio'] dengan urutan descending yaitu dari nilai tertinggi ke rendah
#melihat 5 data pertama
tokens.sort_values('ham_to_spam_ratio', ascending = False).head()

ham      spam  ham_to_spam_ratio
token                                       
my     0.157801  0.038760           4.071277
gt     0.070626  0.019380           3.644326
lt     0.070035  0.019380           3.613830
but    0.093972  0.027132           3.463526
me     0.165189  0.056202           2.939227

In [169]:
#melihat hasil tokens['ham_to_spam_ratio'] dengan urutan descending yaitu dari nilai tertinggi ke rendah
#melihat 20 data pertama
tokens.sort_values('ham_to_spam_ratio', ascending = False).head(20)

ham      spam  ham_to_spam_ratio
token                                       
my     0.157801  0.038760           4.071277
gt     0.070626  0.019380           3.644326
lt     0.070035  0.019380           3.613830
but    0.093972  0.027132           3.463526
me     0.165189  0.056202           2.939227
ok     0.066489  0.025194           2.639116
he     0.049054  0.019380           2.531206
that   0.122636  0.050388           2.433852
come   0.050827  0.021318           2.384268
it     0.144504  0.063953           2.259510
how    0.069444  0.031008           2.239583
ll     0.058215  0.027132           2.145643
she    0.039007  0.019380           2.012766
going  0.041371  0.021318           1.940683
lor    0.036348  0.019380           1.875532
got    0.051714  0.029070           1.778960
so     0.092790  0.056202           1.651015
when   0.063830  0.038760           1.646809
da     0.031324  0.019380           1.616312
at     0.080969  0.050388           1.606929

In [170]:
#melihat hasil tokens['ham_to_spam_ratio'] dengan urutan descending yaitu dari nilai tertinggi ke rendah
#melihat 5 data terakhir
tokens.sort_values('ham_to_spam_ratio', ascending = False).tail()

ham      spam  ham_to_spam_ratio
token                                       
txt    0.006501  0.238372           0.027273
tone   0.002955  0.110465           0.026751
prize  0.002955  0.129845           0.022759
www    0.003546  0.156977           0.022590
claim  0.002955  0.143411           0.020606

In [171]:
#melihat hasil tokens['ham_to_spam_ratio'] dengan urutan descending yaitu dari nilai tertinggi ke rendah
#melihat 20 data terakhir
tokens.sort_values('ham_to_spam_ratio', ascending = False).tail(20)

ham      spam  ham_to_spam_ratio
token                                            
100         0.003251  0.075581           0.043008
1000        0.002955  0.071705           0.041211
free        0.014184  0.348837           0.040662
co          0.003546  0.087209           0.040662
guaranteed  0.002955  0.073643           0.040127
500         0.002955  0.075581           0.039098
50          0.003842  0.098837           0.038868
16          0.003251  0.085271           0.038121
service     0.003546  0.093023           0.038121
18          0.002955  0.081395           0.036305
cs          0.002955  0.081395           0.036305
nokia       0.003842  0.116279           0.033038
uk          0.003251  0.108527           0.029952
150p        0.002955  0.104651           0.028237
mobile      0.005615  0.199612           0.028128
txt         0.006501  0.238372           0.027273
tone        0.002955  0.110465           0.026751
prize       0.002955  0.129845           0.022759
www         0.003546  0.156977           0.022590
claim       0.002955  0.143411           0.020606

In [172]:
#perbandingan nilai tokens.spam dan tokens.ham
#misalnya untuk token '0121' maka 0.021318 dibagi 0.002955
tokens['spam_to_ham_ratio'] = tokens.spam/tokens.ham

In [173]:
#melihat hasil tokens['spam_to_ham_ratio'] dengan urutan descending yaitu dari nilai tertinggi ke rendah
#melihat 5 data pertama
tokens.sort_values('spam_to_ham_ratio', ascending = False).head()

ham      spam  ham_to_spam_ratio  spam_to_ham_ratio
token                                                          
claim  0.002955  0.143411           0.020606          48.530233
www    0.003546  0.156977           0.022590          44.267442
prize  0.002955  0.129845           0.022759          43.939535
tone   0.002955  0.110465           0.026751          37.381395
txt    0.006501  0.238372           0.027273          36.665962

In [174]:
#melihat hasil tokens['spam_to_ham_ratio'] dengan urutan descending yaitu dari nilai tertinggi ke rendah
#melihat 20 data pertama
tokens.sort_values('spam_to_ham_ratio', ascending = False).head(20)

ham      spam  ham_to_spam_ratio  spam_to_ham_ratio
token                                                               
claim       0.002955  0.143411           0.020606          48.530233
www         0.003546  0.156977           0.022590          44.267442
prize       0.002955  0.129845           0.022759          43.939535
tone        0.002955  0.110465           0.026751          37.381395
txt         0.006501  0.238372           0.027273          36.665962
mobile      0.005615  0.199612           0.028128          35.552020
150p        0.002955  0.104651           0.028237          35.413953
uk          0.003251  0.108527           0.029952          33.386892
nokia       0.003842  0.116279           0.033038          30.268336
18          0.002955  0.081395           0.036305          27.544186
cs          0.002955  0.081395           0.036305          27.544186
service     0.003546  0.093023           0.038121          26.232558
16          0.003251  0.085271           0.038121          26.232558
50          0.003842  0.098837           0.038868          25.728086
500         0.002955  0.075581           0.039098          25.576744
guaranteed  0.002955  0.073643           0.040127          24.920930
free        0.014184  0.348837           0.040662          24.593023
co          0.003546  0.087209           0.040662          24.593023
1000        0.002955  0.071705           0.041211          24.265116
100         0.003251  0.075581           0.043008          23.251586

                                    ##Semoga Bermanfaat 
                                    ##@Raspiani_